##email
#email:
#  activate: ${email.activate}
#  reset:
#    password: ${email.reset.password}
#
## 主键生成器配置信息
##序列号占14位
#sequence:
#  bits: ${sequence.bits}
## 模块号占7位
#mode:
#  bits: ${mode.bits}
## 机器码或者服务实例编号占7位
#workerid.bits: ${workerid.bits}
## 机器码或者服务实例编号
#workerid: ${workerid}
#
#
##OSS账户信息
#oss:
#  accessKeyId: ${oss.accessKeyId}
#  accessKeySecret: ${oss.accessKeySecret}
#  endpoint: ${oss.endpoint}
#  bucketName: ${oss.bucketName}
#
##头像存放虚拟目录
#oss:
#  headpic:
#    folderStr: ${oss.headpic.folderStr}
## 重置密码邮件地址
#oss:
#  email:
#    reset:
#      password: ${pet.email.reset.password}